name: AniVerse
description: "AniVerse - Your infinite universe of anime streaming"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.6.1

  # Video Player
  media_kit: ^1.1.11
  media_kit_video: ^1.2.5
  media_kit_libs_video: ^1.0.5

  # HTTP Client
  dio: ^5.7.0
  
  # Local Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Firebase
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.3
  google_sign_in: ^6.2.2
  cloud_firestore: ^5.5.1
  
  # UI
  cached_network_image: ^3.4.1
  go_router: ^14.6.2
  dynamic_color: ^1.7.0
  
  # Utilities
  intl: ^0.19.0
  path_provider: ^2.1.4
  volume_controller: ^3.4.0
  screen_brightness: ^2.1.7
  flutter_widget_from_html: ^0.17.1
  native_device_orientation: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code generation
  build_runner: ^2.4.13
  hive_generator: ^2.0.1


flutter:
  uses-material-design: true
